export const data = [
    {
        facility: 'Jean Gray',
        district: 'Wakanda',
        deliveryZone: '1',
        cycle: '1',
        startDate: '1999-02-01',
        endDate: '1999-04-01',
    },
    {
        facility: 'Jean Gray',
        district: 'Wakanda',
        deliveryZone: '1',
        cycle: '1',
        startDate: '2000-02-01',
        endDate: '2000-04-01',
    },
    {
        facility: 'Loki',
        district: 'Wakanda',
        deliveryZone: '2',
        cycle: '2',
        startDate: '1998-06-01',
        endDate: '1998-08-01',
    },
    {
        facility: 'Thor',
        district: 'Asgard',
        deliveryZone: '1',
        cycle: '2',
        startDate: '2005-03-01',
        endDate: '2005-05-01',
    },
    {
        facility: 'Thor',
        district: 'Asgard',
        deliveryZone: '1',
        cycle: '1',
        startDate: '2020-03-01',
        endDate: '2020-05-01',
    },
    {
        facility: 'Dr Strange',
        district: 'Asgard',
        deliveryZone: '2',
        cycle: '2',
        startDate: '2005-08-01',
        endDate: '2005-10-01',
    },
    {
        facility: 'Batman',
        district: 'Asgard',
        deliveryZone: '4',
        cycle: '1',
        startDate: '2002-10-01',
        endDate: '2002-12-01',
    },
    {
        facility: 'Wonder Woman',
        district: 'Krypton',
        deliveryZone: '2',
        cycle: '2',
        startDate: '2021-01-01',
        endDate: '2021-03-01',
    },
    {
        facility: 'Superman',
        district: 'Krypton',
        deliveryZone: '3',
        cycle: '2',
        startDate: '2003-07-01',
        endDate: '2003-09-01',
    },
    {
        facility: 'Flash',
        district: 'Krypton',
        deliveryZone: '1',
        cycle: '1',
        startDate: '2005-03-01',
        endDate: '2005-05-01',
    },
    {
        facility: 'Jean Gray',
        district: 'Wakanda',
        deliveryZone: '1',
        cycle: '1',
        startDate: '1999-02-01',
        endDate: '1999-04-01',
    },
    {
        facility: 'Jean Gray',
        district: 'Wakanda',
        deliveryZone: '1',
        cycle: '1',
        startDate: '2000-02-01',
        endDate: '2000-04-01',
    },
    {
        facility: 'Loki',
        district: 'Wakanda',
        deliveryZone: '2',
        cycle: '2',
        startDate: '1998-06-01',
        endDate: '1998-08-01',
    },
    {
        facility: 'Thor',
        district: 'Asgard',
        deliveryZone: '1',
        cycle: '2',
        startDate: '2005-03-01',
        endDate: '2005-05-01',
    },
    {
        facility: 'Thor',
        district: 'Asgard',
        deliveryZone: '1',
        cycle: '1',
        startDate: '2020-03-01',
        endDate: '2020-05-01',
    },
    {
        facility: 'Dr Strange',
        district: 'Asgard',
        deliveryZone: '2',
        cycle: '2',
        startDate: '2005-08-01',
        endDate: '2005-10-01',
    },
    {
        facility: 'Batman',
        district: 'Asgard',
        deliveryZone: '4',
        cycle: '1',
        startDate: '2002-10-01',
        endDate: '2002-12-01',
    },
    {
        facility: 'Wonder Woman',
        district: 'Krypton',
        deliveryZone: '2',
        cycle: '2',
        startDate: '2021-01-01',
        endDate: '2021-03-01',
    },
    {
        facility: 'Superman',
        district: 'Krypton',
        deliveryZone: '3',
        cycle: '2',
        startDate: '2003-07-01',
        endDate: '2003-09-01',
    },
    {
        facility: 'Flash',
        district: 'Krypton',
        deliveryZone: '1',
        cycle: '1',
        startDate: '2005-03-01',
        endDate: '2005-05-01',
    },
]