export const artDrugs = [
    { 
        order: 1,
        drugId: 1,
        recommendedFormulations: '1 ADULT -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Tenofovir/Lamivudine/Efavirenz (TDF/3TC/EFV) 300/300mg/600mg',
        basicUnit:'Pack of 30',
    },
    { 
        order: 2,
        drugId: 2,
        recommendedFormulations: '1 ADULT -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Zidovudine /Lamivudine/Nevirapine (AZT/3TC/NVP) 300mg/150mg/200mg',
        basicUnit:'Pack of 30',
    },
    { 
        order: 3,
        drugId: 3,
        recommendedFormulations: '1 ADULT -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Tenofovir/Lamivudine (TDF/3TC) 300mg/300mg',
        basicUnit:'Pack of 30',
    },
    { 
        order: 4,
        drugId: 4,
        recommendedFormulations: '1 ADULT -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Zidovudine/Lamivudine (AZT/3TC)300mg/150mg',
        basicUnit:'Pack of 30',
    },
    { 
        order: 5,
        drugId: 5,
        recommendedFormulations: '1 ADULT -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Abacavir/Lamivudine (ABC/3TC) 600mg/300mg',
        basicUnit:'Pack of 30',
    },
    { 
        order: 6,
        drugId: 6,
        recommendedFormulations: '1 ADULT -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Efavirenz (EFV) 600mg',
        basicUnit:'Pack of 30',
    },
    { 
        order: 7,
        drugId: 7,
        recommendedFormulations: '1 ADULT -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Nevirapine (NVP) 200mg',
        basicUnit:'Pack of 30',
    },
    { 
        order: 8,
        drugId: 8,
        recommendedFormulations: '1 ADULT -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Atazanavir/Ritonavir (ATV/r) 300mg/100mg',
        basicUnit:'Pack of 30',
    },
    { 
        order: 9,
        drugId: 9,
        recommendedFormulations: '1 ADULT -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Lopinavir/Ritonavir (LPV/r) 200mg/50mg',
        basicUnit:'Pack of 30',
    },
    { 
        order: 10,
        drugId: 10,
        recommendedFormulations: '1 ADULT -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Zidovudine (AZT) 300mg',
        basicUnit:'Pack of 30',
    },
    { 
        order: 11,
        drugId: 11,
        recommendedFormulations: '2 PAEDIATRIC -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Abacavir/Lamivudine (ABC/3TC) 60mg/30mg',
        basicUnit:'Pack of 60',
    },
    { 
        order: 12,
        drugId: 12,
        recommendedFormulations: '2 PAEDIATRIC -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Zidovudine/Lamivudine/Nevirapine (AZT/3TC/NVP) 60mg/30mg/50mg',
        basicUnit:'Pack of 60',
    },
    { 
        order: 13,
        drugId: 13,
        recommendedFormulations: '2 PAEDIATRIC -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Zidovudine/Lamivudine (AZT/3TC) 60mg/30mg',
        basicUnit:'Pack of 60',
    },
    { 
        order: 14,
        drugId: 14,
        recommendedFormulations: '2 PAEDIATRIC -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Efavirenz (EFV) 200mg',
        basicUnit:'Pack of 60',
    },
    { 
        order: 15,
        drugId: 15,
        recommendedFormulations: '2 PAEDIATRIC -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Nevirapine (NVP) 50mg',
        basicUnit:'Pack of 60',
    },
    { 
        order: 16,
        drugId: 16,
        recommendedFormulations: '2 PAEDIATRIC -- RECOMMENDED FORMULATIONS',
        drugFormulations: ' Lopinavir/Ritonavir (LVP/r) 80mg/20mi oral susp',
        basicUnit:'Pack of 60',
    },
    { 
        order: 17,
        drugId: 17,
        recommendedFormulations: '2 PAEDIATRIC -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Lopinavir/Ritonavir (LVP/r) 100mg/25mg',
        basicUnit:'Pack of 60',
    },
    { 
        order: 18,
        drugId: 18,
        recommendedFormulations: '2 PAEDIATRIC -- RECOMMENDED FORMULATIONS',
        drugFormulations: 'Abacavir (ABC) 60mg',
        basicUnit:'Pack of 60',
    },
    { 
        order: 19,
        drugId: 19,
        recommendedFormulations: '3 E-MTCT ONLY FORMULATIONS',
        drugFormulations: 'Nevirapine (NVP) 10mg/ml oral susp.',
        basicUnit:'100 ml',
    },
    { 
        order: 20,
        drugId: 20,
        recommendedFormulations: '4 OTHER FORMULATIONS',
        drugFormulations: 'Cotrimoxazole 960mg',
        basicUnit:'1000',
    },
    { 
        order: 21,
        drugId: 21,
        recommendedFormulations: '4 OTHER FORMULATIONS',
        drugFormulations: 'Cotrimoxazole 120mg',
        basicUnit:'1000',
    },
    { 
        order: 22,
        drugId: 22,
        recommendedFormulations: '4 OTHER FORMULATIONS',
        drugFormulations: 'Fluconazole oral susp.',
        basicUnit:'28',
    },
    { 
        order: 23,
        drugId: 23,
        recommendedFormulations: '4 OTHER FORMULATIONS',
        drugFormulations: 'Fluconazole IV',
        basicUnit:'35 ml',
    },
    { 
        order: 24,
        drugId: 24,
        recommendedFormulations: '4 OTHER FORMULATIONS',
        drugFormulations: 'Dapsone 100mg',
        basicUnit:'100 ml',
    },
    { 
        order: 25,
        drugId: 25,
        recommendedFormulations: '4 OTHER FORMULATIONS',
        drugFormulations: 'Nevirapine (NVP) 10mg/ml oral susp.',
        basicUnit:'1000',
    },
]
 
export const artRegimens = [
    { 
        order: 1,
        drugId: 1,
        patient: 'Adult',
        line: '1st Line Regimens',        
        name: 'TDF/3TC/NVP',
    },
    { 
        order: 2,
        drugId: 2,
        patient: 'Adult',
        line: '1st Line Regimens',        
        name: 'TDF/3TC/EFV',
    },
    { 
        order: 3,
        drugId: 3,
        patient: 'Adult',
        line: '1st Line Regimens',        
        name: 'AZT/3TC/NVP',
    },
    { 
        order: 4,
        drugId: 4,
        patient: 'Adult',
        line: '1st Line Regimens',        
        name: 'AZT/3TC/EFV',
    },
    { 
        order: 5,
        drugId: 5,
        patient: 'Adult',
        line: '1st Line Regimens',        
        name: 'ABC/3TC/NVP',
    },
    { 
        order: 6,
        drugId: 6,
        patient: 'Adult',
        line: '1st Line Regimens',        
        name: 'ABC/3TC/EFV',
    },
    { 
        order: 7,
        drugId: 7,
        patient: 'Adult',
        line: '1st Line Regimens',        
        name: 'TDF/3TC/AZT',
    },
    { 
        order: 8,
        drugId: 8,
        patient: 'Adult',
        line: '1st Line Regimens',        
        name: 'ABC/3TC/AZT',
    },
    { 
        order: 9,
        drugId: 9,
        patient: 'Adult',
        line: '2nd Line Regimens',        
        name: 'TDF/3TC/ATV/r',
    },
    { 
        order: 10,
        drugId: 10,
        patient: 'Adult',
        line: '2nd Line Regimens',        
        name: 'TDF/3TC/LPV/r',
    },
    { 
        order: 11,
        drugId: 11,
        patient: 'Adult',
        line: '2nd Line Regimens',        
        name: 'AZT/3TC/ATV/r',
    },
    { 
        order: 12,
        drugId: 12,
        patient: 'Adult',
        line: '2nd Line Regimens',        
        name: 'AZT/3TC/LPV/r',
    },
    { 
        order: 13,
        drugId: 13,
        patient: 'Adult',
        line: '2nd Line Regimens',        
        name: 'ABC/3TC/ATV/r',
    },
    { 
        order: 14,
        drugId: 14,
        patient: 'Adult',
        line: '2nd Line Regimens',        
        name: 'ABC/3TC/LPV/r',
    },
    { 
        order: 1,
        drugId: 15,
        patient: 'Paediatric',
        line: '1st Line Regimens',        
        name: 'ABC/3TC/NVP',
    },
    { 
        order: 2,
        drugId: 16,
        patient: 'Paediatric',
        line: '1st Line Regimens',        
        name: 'ABC/3TC/EFV',
    },
    { 
        order: 3,
        drugId: 17,
        patient: 'Paediatric',
        line: '1st Line Regimens',        
        name: 'AZT/3TC/NVP',
    },
    { 
        order: 4,
        drugId: 18,
        patient: 'Paediatric',
        line: '1st Line Regimens',        
        name: 'AZT/3TC/EFV',
    },
    { 
        order: 5,
        drugId: 19,
        patient: 'Paediatric',
        line: '1st Line Regimens',        
        name: 'AZT/3TC/ABC',
    },
    { 
        order: 6,
        drugId: 20,
        patient: 'Paediatric',
        line: '2nd Line Regimens',        
        name: 'ABC/3TC/LPV/r',
    },
    { 
        order: 7,
        drugId: 21,
        patient: 'Paediatric',
        line: '2nd Line Regimens',        
        name: 'AZT/3TC/LPV/r',
    },
]
 
export const fluconazole = [
    { 
        order: 1,
        drugId: 1,        
        condition: 'Acute cryptococcal meningitis',
    },
    { 
        order: 2,
        drugId: 2,      
        condition: 'Cryptococcal meningitis patients treated on maintenance therapy ',
    },
    { 
        order: 3,
        drugId: 3,     
        condition: 'Esophageal candidiasis ',
    },
]

export const otherDrugs = [
    { 
        order: 1,
        drugId: 1,        
        name: 'Cotrimoxazole (Pre-ART and ART)',
    },
    { 
        order: 2,
        drugId: 2,     
        name: 'Dapsone',
    },
]